FSAR-10: Services hero
FoodStandardsAgency/fsa-pattern-library-source pull request #107
Opened 2021-11-10 14:43 UTC by EmilyHazlehurst

- Only display title on service links if there is one.
- Add new examples to hero.stories.js
- Styling for the services hero
- Update twig template to include services section

2021-11-10 17:54 UTC, c-ancia requested changes

2021-11-10 17:54 UTC, c-ancia commented on src/components/general/Hero/hero.html.twig
> +<section class="hero {{ type }}{{ serviceType ? ' hero--services-' ~ serviceType : '' }}">
Could we use div instead of section please? I know it makes sense semantically but we have globally divs on every components.

2021-11-10 17:54 UTC, c-ancia commented on src/components/landing/ServiceLinks/serviceLinks.html.twig
> +        {% if title %}
isn't it covered by the if on line 3? 🤔  just wondering why both ifs? Is it like in case title is defined but as empty string? But then, do we want to display the blocks if there's no title at all?

2021-11-10 17:54 UTC, c-ancia commented on src/components/general/Hero/hero.html.twig
> +          <div class="hero__services__wrapper hero__services__wrapper--{{ columns }}-columns">
quick question: isn't the number of columns handled in the services component itself? Can you pass a parameter to it? Just wondering if there's a way of saving all the trouble to do it in the hero. I assume there's the case of 4 columns + image but it could be controlled by a condition to the parameter? 🤔

2021-11-10 18:14 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.html.twig
> +<section class="hero {{ type }}{{ serviceType ? ' hero--services-' ~ serviceType : '' }}">
I think Rachael asked for us to use section as it’s what’s used on the site currently, but I’ll ask and update if she’s happy for it to be a div.

2021-11-10 18:16 UTC, EmilyHazlehurst commented on src/components/landing/ServiceLinks/serviceLinks.html.twig
> +        {% if title %}
I didn’t see that, but it wasn’t working as the dots below the title were still appearing when there was no title. I’ll take another look and see if I can get it to work with a single if statement.

2021-11-10 18:25 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.html.twig
> +          <div class="hero__services__wrapper hero__services__wrapper--{{ columns }}-columns">
The number of columns is handled by the service links component, but the hero displays them slightly differently depending on the number of columns and whether that’s combined with an image. 

Sorry, what do you mean by a condition to the parameter? Do you mean handle the CSS for the service links in the serviceLinks.scss file, based on a parameter sent to the service link component? I could potentially refactor it as there’s time left on the ticket, but it would hold up Rachael’s amends to the other hero tickets as I’m on support tomorrow.

2021-11-10 18:26 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.html.twig
> +          <div class="hero__services__wrapper hero__services__wrapper--{{ columns }}-columns">
Just to be clear, i’m not actually setting the number of columns here, it’s still handled in the service links component, I’m just using the modifier in the css so that I can change the positioning based on the number of columns.

2021-11-10 20:47 UTC, rachael-sutherland commented on src/components/general/Hero/hero.html.twig
> +<section class="hero {{ type }}{{ serviceType ? ' hero--services-' ~ serviceType : '' }}">
On the live site paragraphs are divs and the hero is a section. Of course Carole should make final decision

2021-11-10 20:48 UTC, rachael-sutherland commented on src/components/general/Hero/hero.html.twig
> +          <div class="hero__services__wrapper hero__services__wrapper--{{ columns }}-columns">
It would be good to remove the container if we can?

2021-11-11 18:43 UTC, c-ancia requested changes

2021-11-11 18:43 UTC, c-ancia commented on src/components/general/Hero/hero.scss
> +      width: 101%;
a bit surprised by 101%. Is it necessary? 🤔

2021-11-11 18:43 UTC, c-ancia commented on src/components/general/Hero/hero.scss
> +      background-size: 150%;
also here, why 150% ? 🤔

2021-11-12 13:26 UTC, PeterBerryman approved these changes

2021-11-12 13:26 UTC, merged