Feature/fsar 24 document downdload
FoodStandardsAgency/fsa-pattern-library-source pull request #135
Opened 2021-11-26 09:24 UTC by Yinuo-M

- Create storybook component
- Create article two column layout and article page
- Add the component to the article page

2021-11-29 11:15 UTC, c-ancia requested changes

2021-11-29 11:15 UTC, c-ancia commented on src/components/general/DocumentDownload/documentDownload.stories.js
> +};
Can you add an example with multiple regions please?

2021-11-29 11:15 UTC, c-ancia commented on src/index.js
> +import './layout/articleTwoColumn/articleTwoColumn';
I'm picky here but I think I'd name it ContentLayout. So can you change the whole naming accordingly please?

2021-12-02 09:04 UTC, Yinuo-M commented on src/components/general/DocumentDownload/documentDownload.html.twig
> +{% endif %}
Yes I've moved endif

2021-12-02 09:06 UTC, Yinuo-M commented on src/components/general/DocumentDownload/documentDownload.html.twig
> +  {% set region_first = region|slice(0, region|length - 1) %}
No, the second argument of slice specifies how many items you want to include, not an index

2021-12-02 09:14 UTC, Yinuo-M commented on src/components/general/DocumentDownload/documentDownload.html.twig
> +      <span class="visually-hidden"> {{ as }} {{ format }}({{ new_window }})</span>
So the "view" and "as format new window" are there for screenreaders to read out. E.g. if it's a PDF document called "Cats", screenreaders will say 'view Cats as PDF in a new window', which makes more sense and provides more context for visually impaired users. I copied this technique from the [live fsa site ](http://foodgovukstg.prod.acquia-sites.com/business-guidance/applying-for-approval-of-a-meat-establishment)

2021-12-02 09:25 UTC, Yinuo-M commented on src/components/general/DocumentDownload/documentDownload.stories.js
> +};
done

2021-12-02 09:28 UTC, Yinuo-M commented on src/index.js
> +import './layout/articleTwoColumn/articleTwoColumn';
Done

2021-12-02 10:11 UTC, c-ancia commented on src/components/general/DocumentDownload/documentDownload.html.twig
> +      <span class="visually-hidden"> {{ as }} {{ format }}({{ new_window }})</span>
Yes, I just meant in the new design, it seems Rachael wants "as PDF" to be visible
https://app.zeplin.io/project/5c6fadbfbc13ad1a90fbd4a8/screen/6151add3489aab13acb225ee

2021-12-02 10:24 UTC, merged