Feature/fsar 165 datepicker component
FoodStandardsAgency/fsa-pattern-library-source pull request #173
Opened 2022-01-04 16:16 UTC by EmilyHazlehurst

2022-01-05 16:15 UTC, c-ancia commented on src/components/form/Select/select.html.twig
> +  <span class="select__label" aria-hidden="true">{{ label }}</span>
@EmilyHazlehurst can you explain why we have 2 labels here please? I couldn't find a reason in the ticket and I see we just use the label on the live site.

2022-01-05 16:17 UTC, c-ancia commented on src/components/general/Header/header.js
> +        //languageSwitcherDesktop.setAttribute('aria-hidden', false);
if we don't use these anymore, I'd suggest removing the whole if else.

2022-01-05 16:31 UTC, c-ancia commented on src/helpers/generateDatepickerContent.js
> +        let days = [...Array(32).keys()];
shouldn't the days be dependent on the month? Or like, is there some kind of validation? should we take the 28 of february in case the user selects 31 feb for instance?

2022-01-05 16:43 UTC, EmilyHazlehurst commented on src/helpers/generateDatepickerContent.js
> +        let days = [...Array(32).keys()];
@c-ancia Sorry, I think when I was doing this I was imagining that the dates would be provided/validated by Drupal so this is just generating it for the sake of the Storybook demo.

I can change it to add the dates and validation on the frontend tomorrow.

2022-01-05 16:47 UTC, EmilyHazlehurst commented on src/components/form/Select/select.html.twig
> +  <span class="select__label" aria-hidden="true">{{ label }}</span>
@c-ancia 

The article I was reading about accessible dropdowns suggested adding a hidden, accessible label as well as the visible label. The visible label might say 'day' which makes sense if you can see the context, but the accessible label which is read by screen readers could say 'select a day from the datepicker' to contextualise it, if that makes sense?

It's easy/quick to remove though so I'll change it to be inline with the current site :)

2022-01-05 16:49 UTC, c-ancia commented on src/components/form/Select/select.html.twig
> +  <span class="select__label" aria-hidden="true">{{ label }}</span>
@EmilyHazlehurst thanks, that's good to know! before you do any changes, I'd like to have Rachael's & Anna's opinions on it.

2022-01-05 16:50 UTC, c-ancia commented on src/helpers/generateDatepickerContent.js
> +        let days = [...Array(32).keys()];
okay, thanks! I was just double checking, no need to change.

2022-01-14 14:21 UTC, c-ancia requested changes

2022-01-14 14:21 UTC, c-ancia commented on src/components/search/Accordion/accordion.html.twig
> +    <button class="accordion__button {{ open ? "accordion__button--expanded" : "" }}"
I'm picky but can you do the ternary "glued" to the accordion_button class please and add the space to the class in the ternary?  that way we avoid trailing spaces. Thanks!

2022-01-14 14:21 UTC, c-ancia commented on src/components/search/Accordion/accordion.html.twig
> +  <div class="accordion__fields {{ open ? "accordion__fields--active" : "" }}" id={{ fields_id }}>
same request here please.

2022-01-14 14:21 UTC, c-ancia commented on src/components/search/Accordion/react/accordion.html.twig
> +    <button class="accordion__button {{ open ? "accordion__button--expanded" : "" }}"
same request as the non react component please.

2022-01-14 14:21 UTC, c-ancia commented on src/components/search/Accordion/react/accordion.html.twig
> +  <div class="accordion__fields {{ open ? "accordion__fields--active" : "" }}" id={{ fields_id }}>
and here too please

2022-01-14 14:21 UTC, c-ancia commented on src/components/search/Accordion/react/accordion.html.twig
> +</fieldset>
more of a general question here: what is the difference with the non react template please? Seeing in the PR is not easy (have to scroll to compare). 🙈

2022-01-14 14:21 UTC, c-ancia commented on src/components/search/Datepicker/datepicker.html.twig
> +          <option value="{{ loop.index}}" data-option-value="{{ day }}">{{ day }}</option>
can you add a space after loop.index and before }} please?

2022-01-14 14:21 UTC, c-ancia commented on src/components/search/Datepicker/datepicker.js
> +      const shortMonths = [9, 4, 5, 11];
shouldn't it be 4, 6, 9, 11? 5 (May) has 31 days.

2022-01-14 14:23 UTC, c-ancia commented
One more question: any reason why you removed your select component? Is it because there is the Dropdown one? You could have still reused the select in the Datepicker one. It seems 3 selects are duplicated now, unless they all differ from each others? Didn't notice a real difference.

2022-01-14 14:50 UTC, EmilyHazlehurst commented
> One more question: any reason why you removed your select component? Is it because there is the Dropdown one? You could have still reused the select in the Datepicker one. It seems 3 selects are duplicated now, unless they all differ from each others? Didn't notice a real difference.

It was purely because it's easier to manage the dates on the react side when you're working with static elements. In this case because the datepicker will always have a day, month and year select it was easier to add three selects with set names (day/month/year) than to pass these values through the filter header, datepicker then the select. Given that the select style is unique to the datepicker I didn't see any issues removing it. 

I can add it back in if we feel like we'll need it, but I think I'd rather get this into testing first and make those changes alongside any amends since it's been stuck on the board for a while.

2022-01-14 14:51 UTC, EmilyHazlehurst commented on src/components/search/Datepicker/datepicker.html.twig
> +          <option value="{{ loop.index}}" data-option-value="{{ day }}">{{ day }}</option>
Added.

2022-01-14 14:53 UTC, EmilyHazlehurst commented on src/components/search/Accordion/react/accordion.html.twig
> +</fieldset>
It's for the component reference. The react template has to use ../../ rather than the @components/ that the normal Storybook template uses to reference embedded components.

This is what was done for the FiltersHeader but let me know if that's wrong :)

2022-01-14 15:00 UTC, c-ancia commented
> > One more question: any reason why you removed your select component? Is it because there is the Dropdown one? You could have still reused the select in the Datepicker one. It seems 3 selects are duplicated now, unless they all differ from each others? Didn't notice a real difference.
> 
> It was purely because it's easier to manage the dates on the react side when you're working with static elements. In this case because the datepicker will always have a day, month and year select it was easier to add three selects with set names (day/month/year) than to pass these values through the filter header, datepicker then the select. Given that the select style is unique to the datepicker I didn't see any issues removing it.
> 
> I can add it back in if we feel like we'll need it, but I think I'd rather get this into testing first and make those changes alongside any amends since it's been stuck on the board for a while.

all good, was really out of curiosity :) it makes sense you can leave like this! thank you

2022-01-14 15:00 UTC, c-ancia approved these changes

2022-01-14 15:01 UTC, merged