Feature/fsar 35 region variation block
FoodStandardsAgency/fsa-pattern-library-source pull request #204
Opened 2022-01-19 11:12 UTC by EmilyHazlehurst

Please provide a thorough description of your component and its usage with screenshots.

## Checklist before opening a PR

Before opening a PR, please make sure:

- [ ] your work is in a branch based on and synced with the develop branch.
- [ ] your scss and twig files are imported in the javascript file. Without this, Webpack won't be able to compile them.
- [ ] your newComponent is imported in the index.js file.
- [ ] your folder hierarchy follows the proper structure.
- [ ] your code follows the coding standards and naming conventions defined.
- [ ] your code has been tested as AA accessibility compliant to the WCAG 2.1 AA standard.
- [ ] your code has been tested in all the browsers listed in the GDS browser's list, including IE11.
- [ ] your code has been tested in all the different screensizes defined.

2022-01-20 09:48 UTC, c-ancia requested changes

2022-01-20 09:48 UTC, c-ancia commented on src/components/article/RegionalVariationBlock/regionalVariationBlock.html.twig
> +    {{ wysiwyg_content|striptags('<b>','<a>','<ul>','<ol>','<li>')|raw }}
Any reason why we remove tags? 🤔

2022-01-20 09:48 UTC, c-ancia commented on src/components/article/RegionalVariationBlock/regionalVariationBlock.html.twig
> +  {% if files.length >= 1 %}
I am not sure the files are necessary all in "one block", maybe we'd alternate text & file for instance...

2022-01-20 10:03 UTC, EmilyHazlehurst commented on src/components/article/RegionalVariationBlock/regionalVariationBlock.html.twig
> +    {{ wysiwyg_content|striptags('<b>','<a>','<ul>','<ol>','<li>')|raw }}
I didn't want to run |raw on any content so I'm allowing the specified tags only. Happy to just have it be {{ wysiwyg_content|raw}} if it's unlikely to be a risk.

2022-01-20 10:04 UTC, EmilyHazlehurst commented on src/components/article/RegionalVariationBlock/regionalVariationBlock.html.twig
> +  {% if files.length >= 1 %}
Do you know how the content will be coming from Drupal? None of the designs have separated files/text so I figured there would be a wysiwyg field and a files field.

2022-01-20 10:07 UTC, EmilyHazlehurst commented on src/components/article/RegionalVariationBlock/regionalVariationBlock.html.twig
> +  {% if files.length >= 1 %}
Will the files be embedded in the wysiwyg? That makes this a more complex ticket if that's the case.

2022-01-21 16:42 UTC, c-ancia commented on src/components/article/RegionalVariationBlock/regionalVariationBlock.scss
> +      display: none;
aren't we missing the :before also? we don't want the color bar also on any nested files

2022-01-21 16:54 UTC, merged