Feature/fsar 224 article page and sticky sidebar
FoodStandardsAgency/fsa-pattern-library-source pull request #220
Opened 2022-01-25 11:48 UTC by EmilyHazlehurst

Please provide a thorough description of your component and its usage with screenshots.

## Checklist before opening a PR

Before opening a PR, please make sure:

- [ ] your work is in a branch based on and synced with the develop branch.
- [ ] your scss and twig files are imported in the javascript file. Without this, Webpack won't be able to compile them.
- [ ] your newComponent is imported in the index.js file.
- [ ] your folder hierarchy follows the proper structure.
- [ ] your code follows the coding standards and naming conventions defined.
- [ ] your code has been tested as AA accessibility compliant to the WCAG 2.1 AA standard.
- [ ] your code has been tested in all the browsers listed in the GDS browser's list, including IE11.
- [ ] your code has been tested in all the different screensizes defined.

2022-01-25 12:45 UTC, c-ancia commented
@EmilyHazlehurst your PR contains RegionalVariationBlock. Do you mind creating another branch without it please? I want to make sure we only merge what relates to the ticket please. :)

2022-01-25 12:57 UTC, c-ancia requested changes

2022-01-25 12:57 UTC, c-ancia commented on src/index.js
> +import stickySidebar from './components/article/StickySidebar/stickySidebar';
could these 2 be grouped with the other `components/article` elements please?

2022-01-25 12:57 UTC, c-ancia commented
@EmilyHazlehurst another "general" request: could you comment your Javascript please? Not sure what all the functions are doing exactly. :) Thanks!

2022-01-25 13:16 UTC, EmilyHazlehurst commented on src/index.js
> +import stickySidebar from './components/article/StickySidebar/stickySidebar';
Done

2022-01-25 13:17 UTC, EmilyHazlehurst commented
> @EmilyHazlehurst your PR contains RegionalVariationBlock. Do you mind creating another branch without it please? I want to make sure we only merge what relates to the ticket please. :)
> 
> Edit: unless there is a reason why we have these changes?

There's a reason; they are small amends that Rachael asked for so I figured I'd do them here to save time. 

I can split them out into their own PR if you'd like?

2022-01-25 14:53 UTC, c-ancia commented on src/components/article/StickySidebar/stickySidebar.js
> +    function moveSidebar(mode, hero, leftRegion, el) {
I don't know if we necessarily need to move it, I think we just need to ensure the layout has everything at the right place and in the right order instead.
For instance, the article layout would get (outside of potential hero banner & breadcrumb) a block for the articleHero, a block for the left column & a block for the right column. That way we have the proper layout in mobile, we just need to ensure the articleHero & the right column have the same size/place.

2022-01-25 14:53 UTC, c-ancia commented
> > @EmilyHazlehurst your PR contains RegionalVariationBlock. Do you mind creating another branch without it please? I want to make sure we only merge what relates to the ticket please. :)
> > Edit: unless there is a reason why we have these changes?
> 
> There's a reason; they are small amends that Rachael asked for so I figured I'd do them here to save time.
> 
> I can split them out into their own PR if you'd like?

No it's okay, just wanted to be sure we're not committing old or unwanted code. thanks!

2022-01-26 09:33 UTC, c-ancia requested changes

2022-01-26 09:33 UTC, c-ancia commented on src/components/article/BackTo/backTo.html.twig
> +  <a href="{{ url }}" class="back-to__link" data-fsa-at="{{ label }}">{{ label }}</a>
the data attribute should be lowercased, stripped from any special chars & spaces replaced by hyphens. We could either do it here or make another property for it. Whatever suits you best :)

2022-01-26 15:35 UTC, c-ancia commented on src/components/article/StickySidebar/stickySidebar.js
> +
It doesn't seem like these variables (hero & leftRegion) are used anymore. Can you remove them please?

2022-01-26 16:45 UTC, merged