[FSAR-273] Add JS linting in project & pipeline.
FoodStandardsAgency/fsa-pattern-library-source pull request #279
Opened 2022-02-28 14:46 UTC by spleshka

Please provide a thorough description of your component and its usage with screenshots.

## Checklist before opening a PR

Before opening a PR, please make sure:

- [ ] your work is in a branch based on and synced with the develop branch.
- [ ] your scss and twig files are imported in the javascript file. Without this, Webpack won't be able to compile them.
- [ ] your newComponent is imported in the index.js file.
- [ ] your folder hierarchy follows the proper structure.
- [ ] your code follows the coding standards and naming conventions defined.
- [ ] your code has been tested as AA accessibility compliant to the WCAG 2.1 AA standard.
- [ ] your code has been tested in all the browsers listed in the GDS browser's list, including IE11.
- [ ] your code has been tested in all the different screensizes defined.

2022-02-28 21:27 UTC, c-ancia requested changes

2022-02-28 21:27 UTC, c-ancia commented on src/components/general/Navigation/navigation-accessibility.js
> +  console.log(navigation);
trailing consoleLog.

2022-02-28 21:27 UTC, c-ancia commented on src/components/general/Navigation/navigation-accessibility.js
> +  navigation = document.querySelector('#navigation');
any reason why this became a let instead of a const?

2022-02-28 21:27 UTC, c-ancia commented on src/components/search/Pagination/pagination.stories.js
> +const Template = ({ ...args }) => {
doesn't look like we need to spread here in the end. Can you update please?

2022-02-28 21:27 UTC, c-ancia commented on src/components/search/SearchBar/searchBar.stories.js
> +const Template = ({ ...args }) => {
same here please, must have been the first components.

2022-02-28 21:27 UTC, c-ancia commented on src/components/search/SearchBarHeader/searchBarHeader.stories.js
> +const Template = ({ ...args }) => {
and here

2022-02-28 21:27 UTC, c-ancia commented on src/pages/search/search.stories.js
> +export const Search = ({ ...args }) => {
also here please.

2022-02-28 21:27 UTC, c-ancia commented on src/style-guide/colour/swatches.stories.js
> +export const Colour = ({ ...args }) => {
and here

2022-02-28 21:27 UTC, c-ancia commented on src/style-guide/spacing-and-grid/grid.stories.js
> +export const Grid = ({ ...args }) => {
here too

2022-02-28 21:27 UTC, c-ancia commented on src/style-guide/typography/typography.stories.js
> +export const Typography = ({ ...args }) => {
and finally here please

2022-03-01 07:14 UTC, spleshka commented on src/components/general/Navigation/navigation-accessibility.js
> +  console.log(navigation);
Great catch! Now, after you spotted this, I've configured Eslint to pick up console.log() left in the code and throw an error. So this issue is resolved & made sure it will never happen again for anyone in the future.

2022-03-01 07:15 UTC, spleshka commented on src/components/general/Navigation/navigation-accessibility.js
> +  navigation = document.querySelector('#navigation');
We needed navigation in the global scope for this file, so I defined it in the global scope and then on content load it gets the value assigned.

2022-03-01 09:52 UTC, c-ancia commented on src/components/general/Navigation/navigation-accessibility.js
> +  navigation = document.querySelector('#navigation');
perfect thanks!

2022-03-01 09:53 UTC, c-ancia approved these changes

2022-03-01 11:25 UTC, merged