Feature/fsar 12 landing links
FoodStandardsAgency/fsa-pattern-library-source pull request #29
Opened 2021-09-29 11:28 UTC by Roxana-deeson

2021-09-29 12:22 UTC, PeterBerryman commented on src/pattern-library/components/LandingLinks/landingLinks.scss
> +    display: grid;
@Roxana-deeson this won't work in IE11, we should be using the grid-cols mixin here, so 
`@include grid-cols(2, 4)` for 2 of 4 columns on mobile
`@incliude grid-cols(4)` on tablet etc

2021-09-30 15:34 UTC, c-ancia requested changes

2021-09-30 15:34 UTC, c-ancia commented on src/pattern-library/components/LandingLinks/landingLinks.scss
>      align-items: center;
do you still need these 3 lines?

2021-09-30 15:34 UTC, c-ancia commented on src/pattern-library/components/LandingLinks/landingLinks.scss
> +  // }
if we don't need this anymore, you can just remove it please. :)

2021-09-30 15:34 UTC, c-ancia commented on yarn-error.log
> +Arguments:
can you remove this file please?

2021-09-30 16:17 UTC, Roxana-deeson commented on src/pattern-library/components/LandingLinks/landingLinks.scss
>      align-items: center;
yes, it's centring the svg + text in the parent container

2021-09-30 16:20 UTC, Roxana-deeson commented on src/pattern-library/components/LandingLinks/landingLinks.scss
> +  // }
oops

2021-09-30 16:23 UTC, c-ancia approved these changes

2021-09-30 16:23 UTC, merged