Feature/fhtml 4 chart switch button
FoodStandardsAgency/fsa-pattern-library-source pull request #310
Opened 2022-03-09 14:37 UTC by Yinuo-M

- Add the switch between chart/table button to the ChartBlock component. Add appropriate JS to toggle the text on the button and the visibility of chart/table on button click.
- CSS margin/padding fix for ChartBlock buttons to make it look good on mobile.
- Add the ChartBlock component to the simple article page.

## Checklist before opening a PR

Before opening a PR, please make sure:

- [ ] your work is in a branch based on and synced with the develop branch.
- [ ] your scss and twig files are imported in the javascript file. Without this, Webpack won't be able to compile them.
- [ ] your newComponent is imported in the index.js file.
- [ ] your folder hierarchy follows the proper structure.
- [ ] your code follows the coding standards and naming conventions defined.
- [ ] your code has been tested as AA accessibility compliant to the WCAG 2.1 AA standard.
- [ ] your code has been tested in all the browsers listed in the GDS browser's list, including IE11.
- [ ] your code has been tested in all the different screensizes defined.
- [ ] you have run the `yarn lint` command and fixed any linting errors.
- [ ] you have updated the CHANGELOG.md file with your changes.

2022-03-09 15:42 UTC, c-ancia requested changes

2022-03-09 15:42 UTC, c-ancia commented on CHANGELOG.md
> +- Switch between table/data view button for ChartBlock
Can you actually duplicate this empty template below it, add your changes in this new one and leave the top one empty please? it's just so we always have an example ready to be duplicated :)

2022-03-09 15:42 UTC, c-ancia commented on src/components/article/ChartBlock/chartBlock.scss
> +      margin-bottom: 2rem;
remember we use margin-top only :) can you please change?

2022-03-09 17:47 UTC, Yinuo-M commented on src/components/article/ChartBlock/chartBlock.scss
> +      margin-bottom: 2rem;
I forgot! Done

2022-03-09 17:48 UTC, Yinuo-M commented on CHANGELOG.md
> +- Switch between table/data view button for ChartBlock
Done

2022-03-10 15:03 UTC, c-ancia approved these changes

2022-03-10 15:03 UTC, merged