Feature/fhtml 22 revision log
FoodStandardsAgency/fsa-pattern-library-source pull request #328
Opened 2022-03-17 12:35 UTC by blakey87

New revision log component added, this will show Drupal revisions, the list of logs can be opened and closed, using the button on the top right.
![image](https://user-images.githubusercontent.com/2771242/158808605-d6629fa0-4942-4090-b0aa-4b1350c6e45f.png)

## Checklist before opening a PR

Before opening a PR, please make sure:

- [ ] your work is in a branch based on and synced with the develop branch.
- [ ] your scss and twig files are imported in the javascript file. Without this, Webpack won't be able to compile them.
- [ ] your newComponent is imported in the index.js file.
- [ ] your folder hierarchy follows the proper structure.
- [ ] your code follows the coding standards and naming conventions defined.
- [ ] your code has been tested as AA accessibility compliant to the WCAG 2.1 AA standard.
- [ ] your code has been tested in all the browsers listed in the GDS browser's list, including IE11.
- [ ] your code has been tested in all the different screensizes defined.
- [ ] you have run the `yarn lint` command and fixed any linting errors.
- [ ] you have updated the CHANGELOG.md file with your changes.

2022-03-17 14:50 UTC, c-ancia requested changes

2022-03-17 14:50 UTC, c-ancia commented on src/components/article/RevisionLogBottom/revisionLogBottom.html.twig
> +</div>
can you fix the indentation on this file please? Should be 2 spacings.

2022-03-17 14:50 UTC, c-ancia commented on src/components/article/RevisionLogBottom/revisionLogBottom.html.twig
> +</div>
should we wrap this component in a {% if logs%} or is it handled on Drupal side? 🤔

2022-03-17 19:59 UTC, blakey87 commented on src/components/article/RevisionLogBottom/revisionLogBottom.scss
> +    background: #fff;
Sure pushed the update.

2022-03-17 19:59 UTC, blakey87 commented on src/components/article/RevisionLogBottom/revisionLogBottom.html.twig
> +</div>
How did I miss this!
Pushed the update.

2022-03-18 09:25 UTC, c-ancia commented on CHANGELOG.md
> +- Add new revision log component
can you move it to the new "upcoming release" part please? :)

2022-03-18 10:59 UTC, c-ancia approved these changes

2022-03-18 10:59 UTC, merged