Feature/hacpp 7 tooltip
FoodStandardsAgency/fsa-pattern-library-source pull request #342
Opened 2022-03-28 13:58 UTC by beloglazov91

2022-03-28 15:15 UTC, c-ancia requested changes

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.js
> +    console.log(tooltip.getBoundingClientRect().left);
trailing console log

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +    height: 36px;
can you convert to rems please?

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +    width: 36px;
here too please

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +      height: 36px;
and these 2 too please

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +    width: 11px;
also here (and the width above)

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +      height: 11px;
and here

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +    top: 59px;
and the top too please

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +      width: 15px;
and all of these please (except the border)

2022-03-28 15:15 UTC, c-ancia commented on src/components/form/Tooltip/tooltip.scss
> +      width: 22px;
and also these please (except the border)

2022-03-29 07:36 UTC, beloglazov91 commented
@c-ancia All amends are here :)

2022-03-29 09:14 UTC, merged