HACCP-9: Save page.
FoodStandardsAgency/fsa-pattern-library-source pull request #346
Opened 2022-03-29 13:24 UTC by beloglazov91

2022-03-29 15:43 UTC, c-ancia requested changes

2022-03-29 15:43 UTC, c-ancia commented on src/components/hacpp/SaveProgress/saveProgress.html.twig
> +  <div class="hacpp-save-progress__actions">
hacpp typo in the classes too :)

2022-03-29 15:43 UTC, c-ancia commented on src/components/hacpp/SaveProgress/saveProgress.scss
> +.hacpp-save-progress {
so typo here too please

2022-03-30 06:57 UTC, beloglazov91 commented
@c-ancia Check it again please.

2022-03-30 08:47 UTC, c-ancia requested changes

2022-03-30 08:47 UTC, c-ancia commented on CHANGELOG.md
> +- Add saveProgress component.
Can you sync develop please? it should go in a new section and not the template one. Thanks :)

2022-03-30 08:57 UTC, merged