FSA-814-radio buttons styling
FoodStandardsAgency/fsa-pattern-library-source pull request #491
Opened 2022-11-23 10:44 UTC by Roxana-deeson

- Changed styling of radio input to match the one on gov.uk website
- Used ::before and ::after on the label of the input rather than on the input itself, as per gov.uk
- Kept radio buttons mixin for the focus style

2022-11-25 15:56 UTC, c-ancia requested changes

2022-11-25 15:56 UTC, c-ancia commented on CHANGELOG.md
> +- Changed radio buttons styling to match the ones on gov.uk
Same comment as in the other PR, it is in the wrong version, it should get in the [Upcoming release] - 1971-11-03 section instead. Can you change please?
Thanks!

2022-11-25 15:56 UTC, c-ancia commented on src/lib.scss
> +      }
Could this be placed in the` radio-input` mixin instead of having `@if $input-type == radio {` or is there a reason to keep it here? 🤔

2022-11-28 13:09 UTC, Roxana-deeson commented on src/lib.scss
> +      }
Hey yes, it's in there because the styling is not applied on the input, it's on the label

2022-11-29 14:41 UTC, c-ancia approved these changes

2022-11-29 15:55 UTC, merged