Feature/fsa 851 grey out translation link if none
FoodStandardsAgency/fsa-pattern-library-source pull request #518
Opened 2023-01-26 14:19 UTC by EmilyHazlehurst

Please provide a thorough description of your component and its usage with screenshots.

## Checklist before opening a PR

Before opening a PR, please make sure:

- [ ] your work is in a branch based on and synced with the develop branch.
- [ ] your scss and twig files are imported in the javascript file. Without this, Webpack won't be able to compile them.
- [ ] your newComponent is imported in the index.js file.
- [ ] your folder hierarchy follows the proper structure.
- [ ] your code follows the coding standards and naming conventions defined.
- [ ] your code has been tested as AA accessibility compliant to the WCAG 2.1 AA standard.
- [ ] your code has been tested in all the browsers listed in the GDS browser's list, including IE11.
- [ ] your code has been tested in all the different screensizes defined.
- [ ] you have run the `yarn lint` command and fixed any linting errors.
- [ ] you have updated the CHANGELOG.md file with your changes.

2023-01-26 16:41 UTC, c-ancia requested changes
just a few questions.

Also, is it still selectable via tab key?

2023-01-26 16:41 UTC, c-ancia commented on src/components/general/Header/header.html.twig
> +                       class="header__language-link header__language-link--{{ not english ? "selected" : "" }}">{{ welsh_label }}</a>
should we also get the not has_translation here too?

2023-01-26 16:41 UTC, c-ancia commented on src/components/general/Header/header.html.twig
> +             class="header__language-link header__language-link--{{ not english ? "selected" : "" }}">{{ welsh_label }}</a>
and also here? 🤔

2023-01-27 16:36 UTC, EmilyHazlehurst commented
@c-ancia I've made those changes.

It's not tabbable anymore, no.

2023-01-27 17:22 UTC, c-ancia approved these changes

2023-01-27 17:24 UTC, c-ancia approved these changes

2023-01-27 17:25 UTC, merged