Feature/fsar 107 list sort by
FoodStandardsAgency/fsa-pattern-library-source pull request #9
Opened 2021-09-16 12:58 UTC by Yinuo-M

I have implemented the arrow Rachel designed by using CSS "appearance: none" and background properties. This works across browsers, and theoretically "::ms-expanded {display: none}" should do the job for IE11, but I can't test it on IE11 yet.

2021-09-17 11:33 UTC, c-ancia requested changes

2021-09-17 13:32 UTC, Yinuo-M commented on src/pattern-library/components/SortBy/sortBy.html.twig
> +</div>
Fixed

2021-09-17 13:32 UTC, Yinuo-M commented on src/pattern-library/components/SortBy/arrow-down.svg
> +</svg>
Fixed

2021-09-17 13:36 UTC, Yinuo-M commented on src/pattern-library/components/SortBy/sortBy.scss
> +    }
I don't think it has any impact on accessibility. It only affects the appearance. I tried it on several browsers and it works fine with keyboard and works in exactly the same way as gov.uk's dropdown list.

2021-09-17 14:23 UTC, Yinuo-M commented
I fixed indents and added texts as parameters. Should be alright now!

2021-09-22 12:28 UTC, PeterBerryman approved these changes

2021-09-22 12:28 UTC, merged