Feature/fsar 141 hero without image
FoodStandardsAgency/fsa-pattern-library-source pull request #96
Opened 2021-11-03 16:06 UTC by EmilyHazlehurst

2021-11-03 17:57 UTC, c-ancia requested changes

2021-11-03 17:57 UTC, c-ancia commented on src/components/general/Hero/hero.html.twig
> +                {% include '../Button/button.html.twig' with {
Can you put an absolute path using the @components alias please? It's replaced by webpack afterwards.
There's an example in the breadcrumb template.

2021-11-03 17:57 UTC, c-ancia commented on src/components/general/Hero/Hero.stories.js
> +// export const HeroWithImage = Template.bind({});
I know it's not ideal for your work but can you remove all the commented code for now please?

2021-11-03 17:57 UTC, c-ancia commented on src/components/general/Hero/hero.html.twig
> +      {# {% endif %} #}
also here please.

2021-11-03 17:57 UTC, c-ancia commented on src/components/general/Hero/hero.scss
> +  -webkit-mask-repeat: no-repeat;
is it working properly with other browsers/IE11?

2021-11-03 17:57 UTC, c-ancia commented on src/components/general/Hero/hero.scss
> +  @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
any reason why we remove the pattern for IE? Is it because the mask doesn't apply there?

2021-11-03 17:57 UTC, c-ancia commented on src/components/general/Hero/hero.scss
> +      background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHZlcnNpb249JzEuMSc+PGNpcmNsZSBjeD0nNCcgY3k9JzQnIHI9JzQnIGZpbGw9JwojZmZmZmZmJyAvPjwvc3ZnPg==
I believe you can use the file now :)

2021-11-03 17:57 UTC, c-ancia commented on src/components/general/Hero/hero.scss
> +          background-image: url("data:image/svg+xml;base64,      PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHZlcnNpb249JzEuMSc+PGNpcmNsZSBjeD0nNCcgY3k9JzQnIHI9JzQnIGZpbGw9JyM1MzU2NWEnIC8+PC
also here :)

2021-11-03 17:57 UTC, c-ancia commented on src/layout/fullWidth/fullWidth.html.twig
> +  {% endblock %}
it turns out we use this layout around each component individually (discussed with Rachael), in case they want to change the layout of 1 component only, so you can wrap your hero already in it.

2021-11-03 17:57 UTC, c-ancia commented on src/pages/universalPage/universalPage.html.twig
> +{% block hero %}
since we want each element for the landing/universal pages to have their own wrapper, can you adapt this template please?

2021-11-05 09:42 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.html.twig
> +                {% include '../Button/button.html.twig' with {
Thanks, that's been updated.

2021-11-05 09:42 UTC, EmilyHazlehurst commented on src/components/general/Hero/Hero.stories.js
> +// export const HeroWithImage = Template.bind({});
Done.

2021-11-05 09:42 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.html.twig
> +      {# {% endif %} #}
Done.

2021-11-05 09:44 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.scss
> +  -webkit-mask-repeat: no-repeat;
It doesn't work on IE11, but does on other browsers. I've shared the way it looks on IE11 with Rachael and she's happy with it without the mask and pattern.

2021-11-05 09:44 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.scss
> +  @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
As above (I've shared the way it looks on IE11 with Rachael and she's happy with it without the mask and pattern). The mask doesn't apply, and the pattern looks odd without it.

2021-11-05 09:44 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.scss
> +      background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHZlcnNpb249JzEuMSc+PGNpcmNsZSBjeD0nNCcgY3k9JzQnIHI9JzQnIGZpbGw9JwojZmZmZmZmJyAvPjwvc3ZnPg==
Thank you, I've updated the css :)

2021-11-05 09:44 UTC, EmilyHazlehurst commented on src/components/general/Hero/hero.scss
> +          background-image: url("data:image/svg+xml;base64,      PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHZlcnNpb249JzEuMSc+PGNpcmNsZSBjeD0nNCcgY3k9JzQnIHI9JzQnIGZpbGw9JyM1MzU2NWEnIC8+PC
Updated.

2021-11-05 09:45 UTC, EmilyHazlehurst commented on src/layout/fullWidth/fullWidth.html.twig
> +  {% endblock %}
Removed.

2021-11-05 09:46 UTC, EmilyHazlehurst commented on src/pages/universalPage/universalPage.html.twig
> +{% block hero %}
Thanks Carole, the full width template is 12 columns and isn't truly full width so I can't wrap my hero in it as mine needs to be full screen width.

2021-11-05 15:29 UTC, c-ancia requested changes

2021-11-05 15:29 UTC, c-ancia commented on src/pages/universalPage/universalPage.html.twig
> +{% block hero %}
I'm not sure I get what you mean? We don't have the block hero anymore in fullwidth do we?

2021-11-05 16:29 UTC, EmilyHazlehurst commented on src/pages/universalPage/universalPage.html.twig
> +{% block hero %}
I've updated this so that the hero example is on the landing page instead.

2021-11-05 17:14 UTC, merged